### ISSUE TITLE
ITV plug in.

### ISSUE THREAD

**Issue by BonitaRed** [catchup4kodi/catchup4kodi#12]
Been working really well but now it’s brilliant on catch up but won’t play live streams. Any ideas?
Thanks

**Comment by alistair-low** [comment]
I have the same issue. This is the error in the Kodi log:

```
2019-05-04 14:27:22.424 T:20436 WARNING: CAddonSettings[plugin.video.itv]: cannot reference separator setting in old setting condition "!eq(3,true)" for "hls"
2019-05-04 14:27:22.424 T:20436 WARNING: CAddonSettings[plugin.video.itv]: failed to parse enable condition "!eq(3,true)" of old setting definition for "hls"
2019-05-04 14:27:35.365 T:8628 WARNING: CAddonSettings[plugin.video.itv]: cannot reference separator setting in old setting condition "!eq(3,true)" for "hls"
2019-05-04 14:27:35.365 T:8628 WARNING: CAddonSettings[plugin.video.itv]: failed to parse enable condition "!eq(3,true)" of old setting definition for "hls"
2019-05-04 14:27:38.296 T:8896 WARNING: CAddonSettings[plugin.video.itv]: cannot reference separator setting in old setting condition "!eq(3,true)" for "hls"
2019-05-04 14:27:38.296 T:8896 WARNING: CAddonSettings[plugin.video.itv]: failed to parse enable condition "!eq(3,true)" of old setting definition for "hls"
2019-05-04 14:27:40.556 T:30704 WARNING: CAddonSettings[plugin.video.itv]: cannot reference separator setting in old setting condition "!eq(3,true)" for "hls"
2019-05-04 14:27:40.556 T:30704 WARNING: CAddonSettings[plugin.video.itv]: failed to parse enable condition "!eq(3,true)" of old setting definition for "hls"
2019-05-04 14:27:40.557 T:30704 WARNING: CAddonSettings[plugin.video.itv]: cannot reference separator setting in old setting condition "!eq(3,true)" for "hls"
2019-05-04 14:27:40.557 T:30704 WARNING: CAddonSettings[plugin.video.itv]: failed to parse enable condition "!eq(3,true)" of old setting definition for "hls"
2019-05-04 14:27:40.855 T:30704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Alistair\AppData\Roaming\Kodi\addons\plugin.video.itv\default.py", line 1149, in <module>
                                                PLAY_STREAM(name,url,iconimage)
                                              File "C:\Users\Alistair\AppData\Roaming\Kodi\addons\plugin.video.itv\default.py", line 252, in PLAY_STREAM
                                                rtmp=re.compile('<MediaFiles base="(.+?)"').findall(response)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-05-04 14:27:40.898 T:25472   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.itv/?url=sim1&mode=7&name=ITV1&iconimage=C%3A%5CUsers%5CAlistair%5CAppData%5CRoaming%5CKodi%5Caddons%5Cplugin.video.itv%5Cart%2F1.png]
```

**Comment by itekweni** [comment]
Looks like this addon has been abandoned
